# @package _global_
# Task go2-walk-stairs: skrl.ppo, train_backend=torch delta.
defaults:
  - /task/go2-walk-stairs/skrl.ppo@_global_
  - _self_
task:
  train_backend: torch
algo:
  agent:
    rollouts: 24
    learning_rate: 0.0003
    learning_rate_scheduler_kwargs:
      kl_threshold: 0.01
